  build:
    stage: build
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/buildDocker.sh latest
    only:
      - master
  publish:
    stage: publish
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/publish.sh latest
    only:
      - master
  buildTag:
    stage: build
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/buildDocker.sh $CI_COMMIT_REF_NAME
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
    
  publishTag:
    stage: publish
    tags: 
      - dockerfasibio
    image: docker
    script:
      - sh -x ./dockerize/publish.sh $CI_COMMIT_REF_NAME
    only:
      - /^([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/
      - /^rc_([0-9]{0,3})\.([0-9]{0,3})\.([0-9]{0,3})$/

  stages: 
    - build
    - publish