version: '3'
services: 
  subscriber:
    restart: always
    build: ../testSubscriber/.
    expose:
      - 8001
  pubsub: 
    restart: always
    build: ../../.
    expose:
      - 8000
    ports:
      - 8000:8000
    environment: 
      - mongoDbPath=mongodb://mongodb:27017
  mongodb: 
    image: mongo